services:
  mongo:
    image: mongo:8
    container_name: akai-recruitment-app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
      MONGO_INITDB_DATABASE: akai-recruitment-app
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - akai-recruitment-app-data:/data/db

volumes:
  akai-recruitment-app-data: