services:
  mysql:
    image: mysql:9.3
    container_name: akai-recruitment-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: akai-recruitment-app
      # MYSQL_USER: user
      # MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - akai-recruitment-app-data:/var/lib/mysql

volumes:
  akai-recruitment-app-data:
